CREATE TABLE "agents" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL
);

CREATE TABLE "shop" (
	"id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL,
	"address"	TEXT
);

CREATE TABLE "bill" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"createdOn"	TEXT NOT NULL,
	"dueOn"	TEXT,
	"amount"	REAL NOT NULL,
	"shopId"	INTEGER NOT NULL,
	"agentId"		INTEGER NOT NULL,
	FOREIGN KEY("shopId") REFERENCES "shop"("id") ON DELETE CASCADE,
	FOREIGN KEY ("agentId") REFERENCES "agents"("id") ON DELETE CASCADE
);

CREATE TABLE "bill_payment" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"dueOn"	TEXT NOT NULL,
	"paidOn"	TEXT NOT NULL,
	"paidAmount"	REAL NOT NULL,
	"billId"	INTEGER NOT NULL,
	"isPaid"	INTEGER,
	FOREIGN KEY("billId") REFERENCES "bill"("id") ON DELETE CASCADE
);